---
title: "Introduction"
output: pdf_document
bibliography: bib/bibliography.bib
---

## Motivating Example: Combatting Economic Exclusion

Predictive modeling using spatial dependence has been employed extensively in recent years, notably in Crime Prediction [@Almanie2015]. However, a key deficiency of many spatial models are their use of arbitrarily defined geographic regions, such as zip codes, political districts, police precincts, state lines, neighborhoods, etc. which diminish and obscure potentially valuable insights. Worse yet, many predictive models ignore and exclude spatial dependence, violating one of the basic tenets of geography: the direct relationship between distance and likeness [@Miller2015].


Income inequality may be a central challenge of our time. Researchers at the Urban Institute [@urban2016] recently identified the socio-economic phenomenon of “Economic Exclusion” as one compelling explanation for the recent rise in inequality in the US. Vulnerable populations (disproportionately communities of color, immigrants, refugees, and women), who are displaced by localized economic prosperity enter into a gradual cycle of diminished access to good jobs, good schools, health care facilities, public spaces, etc. This systematic denial causes enduring and self-reinforcing poverty over the course years and even generations, gradually entrenching income inequality and general unrest.

One way to practically combat economic exclusion is to focus on preventing displacement, however, detecting gentrification at an early enough stage can be a daunting task. When an area experiences economic growth, increased housing demands and subsequent affordability pressures can lead to evictions of low-income families and small businesses. Government agencies and nonprofits tend to intervene once displacement is already underway, and after-the-fact interventions can be costly and ineffective. There are a host of pre-emptive actions that can be deployed to stem divestment and ensure that existing residents benefit from new investments. Not unlike medical treatment, early detection is key to success. Consequently, in 2016, the Urban Institute put forth a call for research into the creation of “neighborhood-level early warning and response systems that can help city leaders and community advocates get ahead of neighborhood changes" [-@urban2016].

This paper explores novel techniques to predict gentrification in the pursuit of combating displacement and economic exclusion. Modern techniques of data mining, machine learning and predictive modeling are applied to datasets describing property values and sale prices in New York City. We explore the viability of using spatial lags, i.e., variables created from physically proximate observations, as features in a machine learning predictive model. 

## Geo-spatial Data

The world has seen an unprecedented amount of geospatial data produced in recent years (i.e., data that contain information about where an observation exists or happened). Every day in the U.S., federal, state and local government agencies are making their troves of geo-spatially tagged data available for the benefit of the public. Adequate tools to describe, explore and model such data are in short supply for the data-journalists and data-activists who have become modern mechanisms of public service. It is imperative that research be done and tools created to better harness such data for commercial and public good. 