---
title: "Literature Review"
output:
  pdf_document: 
    keep_tex: true
---

## Lit Review


The world has seen an unprecedented amount of geospatial data produced in recent years (i.e., data that contain information about where an observation exists or happened). Every day in the U.S., federal, state and local government agencies are making their troves of geo-spatially tagged data available for the benefit of the public. Adequate tools to describe, explore and model such data are in short supply for the data-journalists and data-activists who have become modern mechanisms of public service. It is imperative that research be done and tools created to better harness such data for commercial and public good. 

Predictive modeling using spatial dependence has been employed extensively in recent years, notably in Crime Prediction (Almanie et al., 2015). However, a key deficiency of many spatial dependent models are their use of arbitrarily defined geographic regions, such as zip codes, political districts, police precincts, state lines, neighborhoods, etc. which diminish and obscure potentially valuable insights. Worse yet, many predictive models ignore and exclude spatial dependence, violating one of the basic tenets of geography: the direct relationship between distance and likeness (Miller, et al., 2015).   


## sample citations

Sample Citation: [@antipov12] [see: @antipov12, pp. 33-35; also @antipov12, ch. 1 and *passim*]

A minus sign (-) before the @ will suppress mention of the author in the citation. This can be useful when the author is already mentioned in the text:

Antipov says blah [-@antipov12].

You can also write an in-text citation, as follows:

@antipov12 says blah.