---
title: "Background"
output: pdf_document
bibliography: bib/bibliography.bib
header-includes:
  - \setlength{\parindent}{4em}
  - \setlength{\parskip}{0em}
---

## The Spatially-Conscious Machine Learning Model

Things near each other tend to be like each other. This concept is a well-known problem in traditional spatial analysis and is typically referred to as _spatial autocorrelation_. In statistics, this is said to “reduce the amount of information” pertaining to spatially proximate observations as they can, in part, be used to predict each other [@dimaggio2012spatial]. But can spatial features be used in a machine-learning context to make better predictions? This work demonstrates that the addition of "spatial lag" features to machine learning models significantly increases accuracy when predicting real estate sales and sale prices. 

## Motivation: Combating Income Inequality by Predicting Gentrification

Researchers at the Urban Institute [@urban2016] recently identified _economic exclusion_ as a powerful contributor to income inequality in the United States. Economic exclusion can be defined as follows: vulnerable populations--disproportionately communities of color, immigrants, refugees, and women--who are physically displaced by local economic prosperity enter a continuous cycle of diminished access to good jobs, good schools, health care facilities, public spaces, and other economic and social resources. Diminished access leads to more poverty, which leads to more displacement. This self-reinforcing cycle of poverty and exclusion gradually exacerbates income inequality over the course years and generations. What can be done to intervene?

Stopping Economic Exclusion requires preventing displacement. _Displacement_ can be thought of as the negative consequence of gentrification, where affordability pressures force vulnerable populations to relocate due to localized economic prosperity [@Clay1979]. Reliably predicting gentrification would be a valuable tool for preventing displacement at an early stage; however, such a task has proven difficult historically. 

When an area experiences economic growth, increased housing demands and subsequent affordability pressures can lead to voluntary or involuntary relocation of low-income families and small businesses. Government agencies and nonprofits tend to intervene once displacement is already underway, and after-the-fact interventions can be costly and ineffective. Several preemptive actions exist which can be deployed to stem divestment and ensure that existing residents benefit from local prosperity. Potential interventions include job training, apprenticeships, subsidies, zoning laws, charitable aid, matched savings programs, financial literacy coaching, homeowner assistance, housing vouchers, and more [@urban2016]. Not unlike medical treatment, early detection is the key to success. 

Consequently the Urban Institute published a series of essays in 2016 outlining the few ways city governments employ "Big data and crowdsourced data" to identify vulnerable individuals and connect them with the proper services and resources, noting that "much more could be done" [@urban2016]. This work seeks to further the research into using free, open data, open-source software and cutting-edge techniques to predict trends in gentrification, with the aim of identifying high-risk households and areas in need of intervention. 

To date, many government agencies have demonstrated the benefits of applied predictive modeling, ranging from prescription drug abuse prevention to homelessness intervention to recidivism reduction [@Ritter2013]. However, few if any examples exist of large-scale, systematic applications of data analysis to aid vulnerable populations experiencing displacement. This paper belongs to an emerging trend known as the “science of cities” which aims to use large data sets and advanced simulation and modeling techniques to understand and improve urban patterns and how cities function [@Batty2013]. 

This work explores techniques that can dramatically boost the accuracy of existing gentrification prediction models. We use real estate transactions in New York City, both their occurrence (probability of sale) and their dollar amount (sale price per square foot) as a proxy for gentrification. The technique marries the use of machine-learning predictive modeling with "spatial-lag" features typically seen in geographically-weighted regressions (GWR). We employ a two-step modeling process in which we 1) determine the optimal building types and geographies suited to our feature engineering assumptions and 2) perform a comparative analysis across several state-of-the-art algorithms (generalized linear model, random forest, gradient boosting machine, and artificial neural network). We conclude that spatially-conscious machine learning models consistently outperform traditional real estate valuation and predictive modeling techniques.

